# Generated by Django 4.1.2 on 2022-10-25 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="createdTime",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tracker",
            name="bezRectorVisa",
            field=models.IntegerField(default=0, verbose_name="Без визы ректора"),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="decanFinans",
            field=models.IntegerField(
                default=0, verbose_name="Требуют финансирования (задачи деканов)"
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="fbp",
            field=models.IntegerField(default=0, verbose_name="ФБП"),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="fcep",
            field=models.IntegerField(default=0, verbose_name="ФКЭП"),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="fgs",
            field=models.IntegerField(default=0, verbose_name="ФГС"),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="naSoglAdv",
            field=models.IntegerField(default=0, verbose_name="На согласовании ООС"),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="naSoglDecan",
            field=models.IntegerField(
                default=0, verbose_name="На согласовании деканов"
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="naSoglHr",
            field=models.IntegerField(default=0, verbose_name="На согласовании HR"),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="naSoglLearn",
            field=models.IntegerField(
                default=0,
                verbose_name="На согласовании молодежной учебная деятельность",
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="naSoglProdject",
            field=models.IntegerField(
                default=0, verbose_name="На согласовании проектного"
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="naSoglScience",
            field=models.IntegerField(default=0, verbose_name="На согласовании наука"),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="naSoglYung",
            field=models.IntegerField(
                default=0, verbose_name="На согласовании молодежной политики"
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="naSoglredact",
            field=models.IntegerField(
                default=0, verbose_name="На согласовании редакционный отдел"
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="nobody",
            field=models.IntegerField(default=0, verbose_name="Не согласовано никем"),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="paoCan",
            field=models.IntegerField(default=0, verbose_name="Может согласовать ПАО"),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="remake",
            field=models.IntegerField(
                default=0, verbose_name="Отправлено на доработку"
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="remakeAup",
            field=models.IntegerField(
                default=0, verbose_name="Отправлено на доработку АУП"
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="remakeDecan",
            field=models.IntegerField(
                default=0, verbose_name="Отправлено на доработку деканами"
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="remakeRector",
            field=models.IntegerField(
                default=0, verbose_name="Отправлено на доработку ректором"
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="soglDecan",
            field=models.IntegerField(
                default=0, verbose_name="Согласовано только деканами"
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="uf",
            field=models.IntegerField(default=0, verbose_name="ЮФ"),
        ),
    ]
