# Generated by Django 4.1.1 on 2022-10-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default=None, max_length=30, verbose_name='Отдел'),
            preserve_default=False,
        ),
    ]
