# Generated by Django 4.1.1 on 2022-10-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(max_length=30, null=True, verbose_name='Отдел'),
        ),
    ]
