# Generated by Django 4.1.1 on 2022-10-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='post',
            field=models.CharField(max_length=200, null=True, verbose_name='Должность'),
        ),
    ]
